name: Concours_SN
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  pdfx: ^2.6.0


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/foreground.png"
  adaptive_icon_foreground: "assets/icon.png"





# The following section is specific to Flutter packages.
flutter:
  assets:

    # Assets de l'icon
    - assets/ 
    # Assets des concours d'entree
    - assets/epreuves/entree/ept/
    - assets/epreuves/entree/ensa/
    - assets/epreuves/entree/esp/
    - assets/epreuves/entree/ipsl/
    - assets/epreuves/entree/pd/

    # Assets des concours d'excellence
    - assets/epreuves/excellence/excellence_diourbel/

    # Pour Junior Polytech
    - assets/epreuves/excellence/junior_polytech/terminale/physique/
    - assets/epreuves/excellence/junior_polytech/terminale/maths/
    - assets/epreuves/excellence/junior_polytech/terminale/cons_meca/

    - assets/epreuves/excellence/junior_polytech/premiere/physique/
    - assets/epreuves/excellence/junior_polytech/premiere/maths/
    - assets/epreuves/excellence/junior_polytech/premiere/cons_meca/


    # Pour Concours General

    - assets/epreuves/excellence/concours_general/premiere/allemand/
    - assets/epreuves/excellence/concours_general/premiere/anglais/
    - assets/epreuves/excellence/concours_general/premiere/arabe/
    - assets/epreuves/excellence/concours_general/premiere/citoyennete/
    - assets/epreuves/excellence/concours_general/premiere/espagnol/
    - assets/epreuves/excellence/concours_general/premiere/francais/
    - assets/epreuves/excellence/concours_general/premiere/geographie/
    - assets/epreuves/excellence/concours_general/premiere/grec/
    - assets/epreuves/excellence/concours_general/premiere/histoire/
    - assets/epreuves/excellence/concours_general/premiere/italien/
    - assets/epreuves/excellence/concours_general/premiere/latin/
    - assets/epreuves/excellence/concours_general/premiere/maths/
    - assets/epreuves/excellence/concours_general/premiere/physique/
    - assets/epreuves/excellence/concours_general/premiere/portugais/


    - assets/epreuves/excellence/concours_general/terminale/citoyennete/
    - assets/epreuves/excellence/concours_general/terminale/comptabilite/
    - assets/epreuves/excellence/concours_general/terminale/economie/
    - assets/epreuves/excellence/concours_general/terminale/electronique/
    - assets/epreuves/excellence/concours_general/terminale/geographie/
    - assets/epreuves/excellence/concours_general/terminale/histoire/
    - assets/epreuves/excellence/concours_general/terminale/islamiques/
    - assets/epreuves/excellence/concours_general/terminale/maths/
    - assets/epreuves/excellence/concours_general/terminale/philosophie/
    - assets/epreuves/excellence/concours_general/terminale/physique/
    - assets/epreuves/excellence/concours_general/terminale/svt/

  uses-material-design: true

